// Generated by Wrangler on Mon Sep 09 2024 09:31:23 GMT+0900 (GMT+09:00)
// by running `wrangler types`

interface Env {
	generalKV: KVNamespace;
	GOOGLE_AUTH_CALLBACK_URL: string;
	GOOGLE_AUTH_CLIENT_ID: string;
	GOOGLE_AUTH_CLIENT_SECRET: string;
	SESSION_SECRET: string;
	DB: D1Database;
}
