// Generated by Wrangler on Sat Sep 07 2024 23:16:05 GMT+0900 (GMT+09:00)
// by running `wrangler types`

interface Env {
	generalKV: KVNamespace;
	DB: D1Database;
	SESSION_SECRET: string;
	GOOGLE_AUTH_CALLBACK_URL: string;
	GOOGLE_AUTH_CLIENT_ID: string;
	GOOGLE_AUTH_CLIENT_SECRET: string;
}
